### ISSUE TITLE
Testar imagem sem objeto

### ISSUE THREAD

**Issue by BrunoGomesCoelho** [BrunoGomesCoelho/ChainCodes#1]
Dentro da função getPontoInicial, tenho que ter um retorno, até se não existir um objeto.

O problema, é que para alcançar 100% de cobertura do código (aliás, não tenho certeza se isso é necessário mas acho que sim), tenho que testar essa linha.

A única maneira de testar isso, é usando uma imagem PNG do tipo grayscale, com todos os pixels sendo brancos (255). O problema é que não consigui achar esse tipo de imagem online nem criar ela na mão de jeito nenhum :/

Vou tentar falar com o professor hoje e falar se da pra enviar sem o 100%, mas to sem ideias se isso não der certo

**Comment by gmelodie** [comment]
Acho que sei como fazer, qual o tamanho (dimensões) da imagem que você quer?
